(function(a){a.fn.scrollFollow=function(d){_this=a(this);d=d||{};d.container=d.container||"";d.bottomObj=d.bottomObj||"";d.bottomMargin=d.bottomMargin||0;d.marginTop=d.marginTop||0;d.marginBottom=d.marginBottom||0;d.zindex=d.zindex||999;_this.each(function(){a.scrollFollow(this,d)});return _this};a.scrollFollow=function(d,b){var e=a(d),g=b.container?e.closest(b.container):"",f=a(window);if(0>=e.length)return!1;var h=e.position().top,k=e.css("position"),n=""==b.bottomObj||0>=a(b.bottomObj).length?
!1:!0,p=""==g||0>=g.length?!1:!0;f.scroll(function(d){d=e.height();e.css("position")==k&&(h=e.position().top);scrollTop=f.scrollTop();topPosition=0;if(!0==n){var m=a(b.bottomObj).position().top-b.marginBottom-b.marginTop;topPosition=Math.min(topPosition,m-scrollTop-d)}!0==p&&(m=g.position().top+g.height()-b.marginBottom-b.marginTop,topPosition=Math.min(topPosition,m-scrollTop-d));scrollTop>h-b.marginTop?(!0==n||!0==p)&&h+d>m?e.css({position:k,top:h}):window.XMLHttpRequest?e.css({position:"fixed",
top:topPosition+b.marginTop,"z-index":b.zindex}):e.css({position:"absolute",top:scrollTop+topPosition+b.marginTop+"px","z-index":b.zindex}):e.css({position:k,top:h})})};a.fn.inputlimiter=function(d){var b=this;b.mb_substr=function(a,b,d){var h=0;c=0;rstr="";var k=a.length,h=a.replace(/[^\x00-\xff]/g,"**").length;0>b&&(b=h+b);1>d&&(d=h+d);for(h=0;h<k&&!(c>=b);h++){var n=a.charCodeAt(h);c=127>n?c+1:c+2}for(;h<k&&!(n=a.charCodeAt(h),c=127>n?c+1:c+2,rstr+=a.charAt(h),c>=d);h++);return rstr};a(this).each(function(e){0==
a(this).nextAll("div.textlimit").size()&&d&&(_left=a(this).offset().left,_top=a(this).offset().top,_width=a(this).width(),_height=a(this).height(),a('<div class="textlimit">\u4f60\u8fd8\u53ef\u8f93\u5165 n \u4e2a\u5b57</div>').insertAfter(a(this)).css({position:"absolute","z-index":"88",left:_left+1,top:_top+_height-7,background:"#E6FFE8",padding:"3px 2px",width:_width+6,"border-radius":"0 0 2px 2px","text-align":"right","line-height":"100%"}));a(this).bind("propertychange focus keyup input paste",
function(e){e=a(this).attr("max");var g=a(this).val().replace(/[^\x00-\xff]/g,"**").replace(/[\r\n]/g,"").length,g=Math.floor(g/2);g>e&&a(this).val(b.mb_substr(a(this).val(),0,2*e));d&&a(this).nextAll("div.textlimit").html("\u4f60\u8fd8\u53ef\u8f93\u5165 "+(e-g)+" \u4e2a\u5b57")});var g=a(this).nextAll("div.textlimit");a(this).focus(function(){g.fadeIn("slow")});a(this).blur(function(){g.stop(!0,!0)});b.parents("form").submit(function(){g.hide()})})};a.fn.autoTextarea=function(d){var b={maxHeight:100,
minHeight:a(this).height()},e=a.extend({},b,d);return a(this).each(function(){a(this).bind("paste cut keydown keyup focus blur",function(){var a,b=this.style;this.style.height=e.minHeight+"px";this.scrollHeight>e.minHeight&&(e.maxHeight&&this.scrollHeight>e.maxHeight?(a=e.maxHeight,b.overflowY="scroll"):(a=this.scrollHeight,b.overflowY="hidden"),b.height=a+"px")})})}})(jQuery);
(function(a){var d=!1===a.support.boxModel&&a.support.objectAll&&a.support.leadingWhitespace;a.jGrowl=function(b,d){0==a("#jGrowl").size()&&a('<div id="jGrowl"></div>').addClass(d&&d.position?d.position:a.jGrowl.defaults.position).appendTo("body");a("#jGrowl").jGrowl(b,d)};a.fn.jGrowl=function(b,d){if(a.isFunction(this.each)){var g=arguments;return this.each(function(){void 0==a(this).data("jGrowl.instance")&&(a(this).data("jGrowl.instance",a.extend(new a.fn.jGrowl,{notifications:[],element:null,
interval:null})),a(this).data("jGrowl.instance").startup(this));a.isFunction(a(this).data("jGrowl.instance")[b])?a(this).data("jGrowl.instance")[b].apply(a(this).data("jGrowl.instance"),a.makeArray(g).slice(1)):a(this).data("jGrowl.instance").create(b,d)})}};a.extend(a.fn.jGrowl.prototype,{defaults:{pool:0,header:"",group:"",sticky:!1,position:"top-right",glue:"after",theme:"default",themeState:"highlight",corners:"10px",check:250,life:3E3,closeDuration:"normal",openDuration:"normal",easing:"swing",
closer:!0,closeTemplate:"&times;",closerTemplate:"<div>[ close all ]</div>",log:function(){},beforeOpen:function(){},afterOpen:function(){},open:function(){},beforeClose:function(){},close:function(){},animateOpen:{opacity:"show"},animateClose:{opacity:"hide"}},notifications:[],element:null,interval:null,create:function(b,d){d=a.extend({},this.defaults,d);"undefined"!==typeof d.speed&&(d.openDuration=d.speed,d.closeDuration=d.speed);this.notifications.push({message:b,options:d});d.log.apply(this.element,
[this.element,b,d])},render:function(b){var d=this,g=b.message,f=b.options;f.themeState=""==f.themeState?"":"ui-state-"+f.themeState;b=a("<div/>").addClass("jGrowl-notification "+f.themeState+" ui-corner-all"+(void 0!=f.group&&""!=f.group?" "+f.group:"")).append(a("<div/>").addClass("jGrowl-close").html(f.closeTemplate)).append(a("<div/>").addClass("jGrowl-header").html(f.header)).append(a("<div/>").addClass("jGrowl-message").html(g)).data("jGrowl",f).addClass(f.theme).children("div.jGrowl-close").bind("click.jGrowl",
function(){a(this).parent().trigger("jGrowl.beforeClose")}).parent();a(b).bind("mouseover.jGrowl",function(){a("div.jGrowl-notification",d.element).data("jGrowl.pause",!0)}).bind("mouseout.jGrowl",function(){a("div.jGrowl-notification",d.element).data("jGrowl.pause",!1)}).bind("jGrowl.beforeOpen",function(){!1!==f.beforeOpen.apply(b,[b,g,f,d.element])&&a(this).trigger("jGrowl.open")}).bind("jGrowl.open",function(){!1!==f.open.apply(b,[b,g,f,d.element])&&("after"==f.glue?a("div.jGrowl-notification:last",
d.element).after(b):a("div.jGrowl-notification:first",d.element).before(b),a(this).animate(f.animateOpen,f.openDuration,f.easing,function(){!1===a.support.opacity&&this.style.removeAttribute("filter");a(this).data("jGrowl").created=new Date;a(this).trigger("jGrowl.afterOpen")}))}).bind("jGrowl.afterOpen",function(){f.afterOpen.apply(b,[b,g,f,d.element])}).bind("jGrowl.beforeClose",function(){!1!==f.beforeClose.apply(b,[b,g,f,d.element])&&a(this).trigger("jGrowl.close")}).bind("jGrowl.close",function(){a(this).data("jGrowl.pause",
!0);a(this).animate(f.animateClose,f.closeDuration,f.easing,function(){a.isFunction(f.close)?!1!==f.close.apply(b,[b,g,f,d.element])&&a(this).remove():a(this).remove()})}).trigger("jGrowl.beforeOpen");""!=f.corners&&void 0!=a.fn.corner&&a(b).corner(f.corners);1<a("div.jGrowl-notification:parent",d.element).size()&&(0==a("div.jGrowl-closer",d.element).size()&&!1!==this.defaults.closer)&&a(this.defaults.closerTemplate).addClass("jGrowl-closer "+this.defaults.themeState+" ui-corner-all").addClass(this.defaults.theme).appendTo(d.element).animate(this.defaults.animateOpen,
this.defaults.speed,this.defaults.easing).bind("click.jGrowl",function(){a(this).siblings().trigger("jGrowl.beforeClose");a.isFunction(d.defaults.closer)&&d.defaults.closer.apply(a(this).parent()[0],[a(this).parent()[0]])})},update:function(){a(this.element).find("div.jGrowl-notification:parent").each(function(){void 0!=a(this).data("jGrowl")&&(void 0!==a(this).data("jGrowl").created&&a(this).data("jGrowl").created.getTime()+parseInt(a(this).data("jGrowl").life)<(new Date).getTime()&&!0!==a(this).data("jGrowl").sticky&&
(void 0==a(this).data("jGrowl.pause")||!0!==a(this).data("jGrowl.pause")))&&a(this).trigger("jGrowl.beforeClose")});0<this.notifications.length&&(0==this.defaults.pool||a(this.element).find("div.jGrowl-notification:parent").size()<this.defaults.pool)&&this.render(this.notifications.shift());2>a(this.element).find("div.jGrowl-notification:parent").size()&&a(this.element).find("div.jGrowl-closer").animate(this.defaults.animateClose,this.defaults.speed,this.defaults.easing,function(){a(this).remove()})},
startup:function(b){this.element=a(b).addClass("jGrowl").append('<div class="jGrowl-notification"></div>');this.interval=setInterval(function(){a(b).data("jGrowl.instance").update()},parseInt(this.defaults.check));d&&a(this.element).addClass("ie6")},shutdown:function(){a(this.element).removeClass("jGrowl").find("div.jGrowl-notification").trigger("jGrowl.close").parent().empty()},close:function(){a(this.element).find("div.jGrowl-notification").each(function(){a(this).trigger("jGrowl.beforeClose")})}});
a.jGrowl.defaults=a.fn.jGrowl.prototype.defaults})(jQuery);$(function(){$(".topbtn").click(function(){$("html, body").animate({scrollTop:0},500)});$(".bottombtn").click(function(){$("html, body").animate({scrollTop:$("#footer").offset().top},500)})});
$(".sharebtn").live("click",function(a){var d=$(this).closest(".share_root");a=d.find(".tu").attr("src");a=void 0!=a?a:"";var b=a.lastIndexOf("http");0<b&&(a=a.slice(b));b=d.find(".article").clone();b.find("*").each(function(){var a=$(this).text();$(this).replaceWith(a+" ")});d=d.find(".url").attr("href");b=encodeURI(b.html());a=encodeURIComponent(a);if($(this).hasClass("share_sinawb")){var e=encodeURI("3077078248");window.open("http://service.weibo.com/share/share.php?title="+b+"&url="+d+"&source=bookmark&appkey="+
e+"&pic="+a,"","height=500,width=600,top=0,left=0,toolbar=no,menubar=no,resizable=yes,location=yes,status=no")}$(this).hasClass("share_qqwb")&&(e=encodeURI("801293173"),window.open("http://v.t.qq.com/share/share.php?title="+b+"&pic="+a+"&appkey="+e+"&url="+d+"&site=Vzhuti.com","","height=500,width=600,top=0,left=0,toolbar=no,menubar=no,resizable=yes,location=yes,status=no"));$(this).hasClass("share_qzone")&&window.open("http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url="+d+"&title=&pics="+
a+"&desc=&site=&summary="+b,"","height=500,width=600,top=0,left=0,toolbar=no,menubar=no,resizable=yes,location=yes,status=no");$(this).hasClass("share_qq")&&window.open("http://connect.qq.com/widget/shareqq/index.html?url="+d+"&desc="+b+"&pics="+a+"&summary=&site=Vzhuti.com","","height=600,width=800,top=0,left=0,toolbar=no,menubar=no,resizable=yes,location=yes,status=no");$(this).hasClass("share_renren")&&window.open("http://widget.renren.com/dialog/share?resourceUrl="+d+"&title=&pic="+a+"&description="+
b,"","height=720,width=700,top=0,left=0,toolbar=no,menubar=no,resizable=yes,location=yes,status=no")});
function bdshareInit(a){_this=$(a);if(void 0==_this.attr("data")){var d=_this.closest(".share_root");a=d.find(".tu").attr("src");a=void 0!=a?a:"";var b=a.lastIndexOf("http");0<b&&(a=a.slice(b));b=d.find(".article").clone();b.find("*").each(function(){var a=$(this).text();$(this).replaceWith(a+" ")});d=d.find(".url").attr("href");b=b.html();a=encodeURIComponent(a);_this.attr("data","{'text':'"+b+"','title':'"+sitename+" \u5206\u4eab','url':'"+d+"','pic':'"+a+"','comment':'\u9017\u6b7b\u6211\u4e86.....'}")}}
function getCookie(a){var d=document.cookie.indexOf(a+"="),b=d+a.length+1;if((d||a==document.cookie.substring(0,a.length))&&-1!=d)return a=document.cookie.indexOf(";",b),-1==a&&(a=document.cookie.length),unescape(document.cookie.substring(b,a))}function setCookie(a,d,b){b=parseInt(b);var e=new Date;e.setTime(e.getTime()+(0<b?1E3*b:-1E4));document.cookie=a+"="+d+";expires="+e.toGMTString()+";path=/"}
function isCookieEnable(){setCookie("blueria_cookie_test","test",60);var a="test"==getCookie("blueria_cookie_test")?!0:!1;setCookie("blueria_cookie_test","",-1);return a}var shoujian=!1;
function blueria_vote(a,d,b){if(!isNaN(a))if(isCookieEnable())if(null!=getCookie("blueria_vote_"+a))$("#notify").jGrowl("\u60a8\u5df2\u7ecf\u7ed9\u672c\u6587\u6295\u8fc7\u7968\u4e86\uff01",{theme:"smoke"});else if(!0===shoujian)$("#notify").jGrowl("\u5c38\u5144\uff0c\u60a8\u7684\u9f20\u6807\u70b9\u5f97\u4e5f\u592a\u5feb\u4e86\u5427\uff1f\uff01",{theme:"smoke"});else{var e=0;"up"==d?e=1:"down"==d&&(e=-1);shoujian=!0;var g=$(b).parent().find(".num");1>g.size()&&(g=$(b));$.post(ajaxurl,{action:"blueria_vote",
post_ID:a,doit:d},function(a,d){if("success"!=d||0==a)return!1;if(-1==a)return alert("\u975e\u6cd5\u64cd\u4f5c!!!"),!1;var b=parseInt(g.html());g.html(b+e);shoujian=!1})}else $("#notify").jGrowl("\u5f88\u62b1\u6b49\uff0c\u60a8\u4e0d\u80fd\u7ed9\u672c\u6587\u6295\u7968\uff01",{theme:"smoke"})}
$(".videobox").live("click",function(a){if("post_title"==$(a.target).attr("class")||"post_title"==$(a.target).parent().attr("class")||"video_close"==$(a.target).attr("class")||$(this).children().hasClass("flash-replaced"))return 0;a=$(this).find(".videoplayer").attr("src");var d=/sina\.com/.test(a)?"1":"true",b="default"==theme_tpl?440:500,e="default"==theme_tpl?330:375;$(this).find(".videoplayer").flash({src:a,width:b,height:e,wmode:"opaque",allowscriptaccess:"never",allownetworking:"internal",allowFullScreen:"true",
flashvars:{isAutoPlay:"true",autoPlay:d,auto_start:1,auto:1}});$(this).find(".playbtn").hide();$(this).find(".alt").hide();$(this).find(".video_close").show()});$(".video_close").live("click",function(a){$(this).hide();a=$(this).parent();a.find("embed,object").remove();a.find(".playbtn").show();a.find(".alt").show();a.find(".tu").parent().unwrap();a.find(".videoplayer").removeClass("flash-replaced")});
$(".gif .imagewrap").live("click",function(a){_this=$(this);src=_this.attr("gif");tu=_this.find(".tu");if(void 0==_this.data("play")){a=_this.css("background-image");var d=a.replace("gifplay.png","loading.gif");_this.attr("palybtn",a);_this.attr("loading",d);_this.attr("src",tu.attr("src"))}1==_this.data("play")?(tu.attr("src",_this.attr("src")),_this.css({"background-image":_this.attr("palybtn")}),_this.data("play",0)):(_this.css({"background-image":_this.attr("loading")}),img=new Image,img.onload=
function(){tu.attr("src",src);_this.css({"background-image":"none"})},img.src=src,_this.data("play",1))});function chkDuoshuo(){try{if("undefined"==typeof DUOSHUO)setTimeout("chkDuoshuo()",800);else if(0===DUOSHUO.visitor.data.user_id){dsLogin(0);try{"function"==typeof eval(ds)&&ds(0)}catch(a){}}else{dsLogin(1);try{"function"==typeof eval(ds)&&ds(1)}catch(d){}}}catch(b){/DUOSHUO.visitor/i.test(b.message)&&setTimeout("chkDuoshuo()",800)}}
function entities(a){return a.replace(/\</g,"&#x3c;").replace(/\>/g,"&#x3e;")}function log(a){"object"==typeof console&&console.log(a)}
function dsLogin(a){0===a?($(".userlogin").show(),$(".usershow").hide(),$(".userlogin .qq").attr({href:DUOSHUO.templates.loginUrl("qq")}),$(".userlogin .weibo").attr({href:DUOSHUO.templates.loginUrl("weibo")})):1===a&&($(".userlogin").hide(),$(".usershow").show(),$(".userinfo .name").html(entities(DUOSHUO.visitor.data.name)),$(".userinfo .avatar").attr({href:DUOSHUO.visitor.data.url}).find("img").attr({src:DUOSHUO.visitor.data.avatar_url}),$(".userinfo .exit").attr({href:DUOSHUO.templates.logoutUrl()}))}
function moreAccount(){return DUOSHUO.openDialog("<h2>\u7ed1\u5b9a\u66f4\u591a\u5e10\u53f7</h2>"+DUOSHUO.templates.serviceList(1)+DUOSHUO.templates.additionalServices(1)+'<div style="clear:both"></div>').el.find(".ds-dialog").css("width","250px").find(".ds-dialog-footer span").html(sitename?sitename:"Yeti\u4e3b\u9898")}
function moreLogin(){return DUOSHUO.openDialog('<div class="ds-dialog-left"><h2>\u793e\u4ea4\u5e10\u53f7\u767b\u5f55</h2>'+DUOSHUO.templates.serviceList()+DUOSHUO.templates.additionalServices()+"</div>").el.find(".ds-dialog").css("width","250px").find(".ds-dialog-footer span").html(sitename?sitename:"Yeti\u4e3b\u9898")}
window.addEventListener&&(document.addEventListener("animationstart",onAnimationStartHandler,!1),document.addEventListener("webkitAnimationEnd",onAnimationStartHandler,!1),document.addEventListener("oAnimationStart",onAnimationStartHandler,!1),document.addEventListener("msAnimationStart",onAnimationStartHandler,!1));
function onAnimationStartHandler(a){"nodeInserted"===a.animationName&&(a=a.target,$(a).attr("style","display:block;float:left;text-decoration:none;border-bottom:medium none;cursor:pointer;position:relative;margin:0;padding: 5px;width:104px;height:78px;text-align:left;outline:medium none;background-image:none;border-left:0 none !important;"),$(a).find(".wumii-image").attr({style:"background:none repeat scroll 0 0 transparent; padding:0;margin:0;width:98px;height:98px;position:relative;clip: rect(0, 98px, 98px, 0);border:medium none;visibility:visible;top:-12px;left:0;",
onload:""}).wrap("<div class='blueria_wumii'></div>"),$(a).find(".wumii-image-border").attr("style","margin:0px;padding:0px;width:auto;height:76px;border:1px solid #FFF;background-color:#FFF;box-shadow:0 0 3px rgba(0, 0, 0, 0.5);"),$(a).find(".wumii-image-title").attr("style","display:none;"))}
(function(a){a.fn.Slide=function(d){var b=a.extend({},a.fn.Slide.deflunt,d),e=1,g=a("."+b.claNav+" li",a(this)),f=a("."+b.claNav+" .next",a(this)),h=a("."+b.claNav+" .prev",a(this)),k=a("."+b.claCon,a(this)),n=k.children().size();d=k.children().first().height();var p=k.children().first().width(),l,m;"scroolY"==b.effect||"scroolTxt"==b.effect?m=d:"scroolX"==b.effect||"scroolLoop"==b.effect?(k.css("width",n*p),m=p):"fade"==b.effect&&k.children().first().css("z-index","1");return this.each(function(){var d=
a(this),q=function(){a.fn.Slide.effect[b.effect](k,g,e,m,b);e++;e*b.steps>=n&&(e=0)};f.click(function(f){a.fn.Slide.effectLoop.scroolLeft(k,g,e,m,b,function(){for(var a=0;a<b.steps;a++)k.find("li:first",d).appendTo(k);k.css({left:"0"})});f.preventDefault()});h.click(function(d){for(var f=0;f<b.steps;f++)k.find("li:last").prependTo(k);k.css({left:-e*b.steps*p});a.fn.Slide.effectLoop.scroolRight(k,g,e,m,b);d.preventDefault()});b.autoPlay&&(l=setInterval(q,b.timer),k.hover(function(){l&&clearInterval(l)},
function(){l&&clearInterval(l);l=setInterval(q,b.timer)}));g.hover(function(){l&&clearInterval(l);e=g.index(this);window.setTimeout(function(){a.fn.Slide.effect[b.effect](k,g,e,m,b)},200)},function(){l&&clearInterval(l);l=setInterval(q,b.timer)})})};a.fn.Slide.deflunt={effect:"scroolY",autoPlay:!0,speed:"normal",timer:1E3,defIndex:0,claNav:"JQ-slide-nav",claCon:"JQ-slide-content",steps:1};a.fn.Slide.effectLoop={scroolLeft:function(a,b,e,g,f,h){a.animate({left:-e*f.steps*g},f.speed,h);b&&b.eq(e).addClass("on").siblings().removeClass("on")},
scroolRight:function(a,b,e,g,f,h){a.stop().animate({left:0},f.speed,h)}};a.fn.Slide.effect={fade:function(a,b,e,g,f){a.children().eq(e).stop().animate({opacity:1},f.speed).css({"z-index":"1"}).siblings().animate({opacity:0},f.speed).css({"z-index":"0"});b.eq(e).addClass("on").siblings().removeClass("on")},scroolTxt:function(a,b,e,g,f){a.animate({"margin-top":-f.steps*g},f.speed,function(){for(var b=0;b<f.steps;b++)a.find("li:first").appendTo(a);a.css({"margin-top":"0"})})},scroolX:function(a,b,e,
g,f,h){a.stop().animate({left:-e*f.steps*g},f.speed,h);b&&b.eq(e).addClass("on").siblings().removeClass("on")},scroolY:function(a,b,e,g,f){a.stop().animate({top:-e*f.steps*g},f.speed);b&&b.eq(e).addClass("on").siblings().removeClass("on")}}})(jQuery);function isIE(){return!!(window.attachEvent&&-1===navigator.userAgent.indexOf("Opera"))}
$(function(){$.jGrowl.defaults.closer=!1;$(".noticebar").Slide({effect:"scroolTxt",speed:"normal",timer:5E3,steps:1,claCon:"notice_content"});$(".weixin").on("mouseover mouseout",function(a){var d=$(this).offset(),b=120<=d.top?d.top-120:0,d=d.left-220;0==$(".weixintip").size()&&$("<div class='weixintip'></div>").css({top:b,left:d-50}).appendTo("body");b=$(".weixintip");if("mouseover"==a.type){if(isIE())return b.css({left:d}).show(),!1;b.animate({left:d,opacity:"show"},200)}if("mouseout"==a.type){if(isIE())return b.hide(),
!1;b.animate({left:d-50,opacity:"hide"},200)}});$(".hotkeys").on("mouseover mouseout",function(a){var d=$(this).offset(),b=d.top+25,d=d.left-250;0==$(".hotkeystip").size()&&$("<div class='hotkeystip'></div>").css({top:b+50,left:d}).appendTo("body");d=$(".hotkeystip");if("mouseover"==a.type){if(isIE())return d.css({top:b}).show(),!1;d.animate({top:b,opacity:"show"},200)}if("mouseout"==a.type){if(isIE())return d.hide(),!1;d.animate({top:b+50,opacity:"hide"},200)}});$(".blogroll").click(function(){$("#links").slideToggle(300);
$("html, body").animate({scrollTop:$("#footer").offset().top},300);return!1});$(".menu li").hover(function(){isIE()||$(".sub-menu",this).animate({top:"22px",opacity:"show"},200)},function(){isIE()||$(".sub-menu",this).stop(!0,!0).animate({top:"35px",opacity:"hide"},200)});$(".shortcut").hover(function(){$(".sub_menu",this).fadeIn(200)},function(){$(".sub_menu",this).fadeOut(200)});$(".bdshare").each(function(){bdshareInit(this)});$(".comment_inputbox").autoTextarea()});
void 0!=stop_external_link&&stop_external_link&&$("a[rel^=nofollow]").live("click mouseover contextmenu",function(a){"click"==a.type&&$("#notify").jGrowl("\u5916\u90e8\u94fe\u63a5\u5df2\u88ab\u7981\u70b9!!!",{theme:"smoke"});"mouseover"==a.type&&$(this).css({cursor:"not-allowed"});return!1});
function updatePanel(a){a.each(function(){bdshareInit($(this).find(".bdshare"));void 0!=typeof bdShare&&bdShare.fn.init();$.scrollFollow($(this).find(".floatbar"),floatOptions);$(this).find(".comment_inputbox").autoTextarea()})}
$(".comment_btn").live("click",function(){var a=$(this).closest(".panel"),d=a.find(".comment_box"),b=a.find(".comment_inputbox"),a=parseInt(d.attr("data-num"));a%2?(d.slideDown(),$("html, body").animate({scrollTop:b.offset().top-300},300),setTimeout(function(){b.focus()},500)):d.slideUp();d.attr("data-num",++a);return!1});
$(".comment_inputbox").live("focusin focusout",function(a){var d=$(this),b=d.closest(".comment_form");"focusin"==a.type&&(b.addClass("active"),d.val()==comment_notice&&d.val(""),initCommentBar(b));"focusout"==a.type&&""==d.val()&&(b.removeClass("active"),d.val(comment_notice))});
function initCommentBar(a){try{if("undefined"==typeof DUOSHUO.visitor.data.user_id)return}catch(d){}0==DUOSHUO.visitor.data.user_id?(a.find(".publish_btn").on("click",function(a){a.stopPropagation();moreLogin()}),a.find(".comment_user img").attr("src",tpl_url+"ui/userlogin_s.png")):(a.find(".comment_user img").attr("src",DUOSHUO.visitor.data.avatar_url),a.find("input[name='author']").val(DUOSHUO.visitor.data.name),a.find("input[name='url']").val(DUOSHUO.visitor.data.url),a.find("input[name='avatar']").val(DUOSHUO.visitor.data.avatar_url))}
$(".publish_btn").live("click",function(){var a=$(this);if(!a.prop("disabled")){var d=a.closest(".comment_form"),b=d.find(".comment_inputbox");b.val()==comment_notice?b.focus():(a.addClass("publishing").prop("disabled",!0),$.ajax({url:tpl_url+"comments-ajax.php",data:d.serialize(),type:"POST",success:function(b){$(b).appendTo(d.prev(".new_commentlist")).slideDown(2E3);d.find(".comment_inputbox").val(comment_notice);a.removeClass("publishing").prop("disabled",!1)}}))}});
$("#comment").live("focusin focusout",function(a){var d=$(this);"focusin"==a.type&&d.val()==comment_notice&&d.val("");"focusout"==a.type&&""==d.val()&&d.val(comment_notice)});
$(function(){var a=tpl_url+"comments-ajax.php";$("#commentform").on("submit",function(){var d=$(this).find("textarea[name='comment']");if(""==d.val()||d.val()==comment_notice)return alert("\u8bf7\u8f93\u5165\u8bc4\u8bba\u5185\u5bb9"),d.focus(),!1;$("#comments-navi .loading").css("display","inline-block");$("#comment_submit").addClass("publishing").prop("disabled",!0);$.ajax({url:a,data:$(this).serialize(),type:"POST",success:function(a){$("#comments-navi .loading").hide();$(a).appendTo(".commentlist").slideDown(2E3);
d.val("");$("#comment_submit").removeClass("publishing").prop("disabled",!1)}});return!1})});
