/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'blueria\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-home' : '&#xe000;',
			'icon-music' : '&#xe001;',
			'icon-camera' : '&#xe002;',
			'icon-image' : '&#xe003;',
			'icon-headphones' : '&#xe004;',
			'icon-play' : '&#xe005;',
			'icon-film' : '&#xe006;',
			'icon-folder' : '&#xe007;',
			'icon-tag' : '&#xe008;',
			'icon-phone' : '&#xe009;',
			'icon-location' : '&#xe00a;',
			'icon-location-2' : '&#xe00b;',
			'icon-envelop' : '&#xe00c;',
			'icon-support' : '&#xe00d;',
			'icon-cart' : '&#xe00e;',
			'icon-screen' : '&#xe00f;',
			'icon-mobile' : '&#xe010;',
			'icon-mobile-2' : '&#xe011;',
			'icon-box-add' : '&#xe012;',
			'icon-box-remove' : '&#xe013;',
			'icon-spinner' : '&#xe014;',
			'icon-lock' : '&#xe015;',
			'icon-wrench' : '&#xe016;',
			'icon-cog' : '&#xe017;',
			'icon-hammer' : '&#xe018;',
			'icon-gift' : '&#xe019;',
			'icon-fire' : '&#xe01a;',
			'icon-leaf' : '&#xe01b;',
			'icon-rocket' : '&#xe01c;',
			'icon-lightning' : '&#xe01d;',
			'icon-cancel-circle' : '&#xe01e;',
			'icon-blocked' : '&#xe01f;',
			'icon-checkmark-circle' : '&#xe020;',
			'icon-checkmark' : '&#xe021;',
			'icon-close' : '&#xe022;',
			'icon-new-tab' : '&#xe023;',
			'icon-share' : '&#xe024;',
			'icon-google-plus' : '&#xe025;',
			'icon-facebook' : '&#xe026;',
			'icon-feed' : '&#xe027;',
			'icon-feed-2' : '&#xe028;',
			'icon-apple' : '&#xe029;',
			'icon-android' : '&#xe02a;',
			'icon-windows' : '&#xe02b;',
			'icon-chrome' : '&#xe02c;',
			'icon-firefox' : '&#xe02d;',
			'icon-IE' : '&#xe02e;',
			'icon-opera' : '&#xe02f;',
			'icon-safari' : '&#xe030;',
			'icon-css3' : '&#xe031;',
			'icon-html5' : '&#xe032;',
			'icon-finder' : '&#xe033;',
			'icon-windows8' : '&#xe034;',
			'icon-file' : '&#xe035;',
			'icon-camera-2' : '&#xe036;',
			'icon-search' : '&#xe037;',
			'icon-thumbs-up' : '&#xe038;',
			'icon-thumbs-down' : '&#xe039;',
			'icon-mouse' : '&#xe03a;',
			'icon-star' : '&#xe03b;',
			'icon-alarm' : '&#xe03c;',
			'icon-gift-2' : '&#xe03d;',
			'icon-user' : '&#xe03e;',
			'icon-airplane' : '&#xe03f;',
			'icon-bookmark' : '&#xe040;',
			'icon-star-2' : '&#xe041;',
			'icon-libreoffice' : '&#xe042;',
			'icon-key' : '&#xe043;',
			'icon-expand' : '&#xe044;',
			'icon-contract' : '&#xe045;',
			'icon-wrench-2' : '&#xe046;',
			'icon-comment' : '&#xe047;',
			'icon-magnifying-glass' : '&#xe048;',
			'icon-eye' : '&#xe049;',
			'icon-left-quote-alt' : '&#xe04a;',
			'icon-right-quote-alt' : '&#xe04b;',
			'icon-directions' : '&#xe04c;',
			'icon-paperplane' : '&#xe04d;',
			'icon-export' : '&#xe04e;',
			'icon-location-3' : '&#xe04f;',
			'icon-share-2' : '&#xe050;',
			'icon-flag' : '&#xe051;',
			'icon-link' : '&#xe052;',
			'icon-cog-2' : '&#xe053;',
			'icon-music-2' : '&#xe054;',
			'icon-cone' : '&#xe055;',
			'icon-rocket-2' : '&#xe056;',
			'icon-comment-2' : '&#xe057;',
			'icon-folder-2' : '&#xe058;',
			'icon-erase' : '&#xe059;',
			'icon-microphone' : '&#xe05a;',
			'icon-thunder' : '&#xe05b;',
			'icon-star-3' : '&#xe05c;',
			'icon-map-marker' : '&#xe05d;',
			'icon-list' : '&#xe05e;',
			'icon-wrench-3' : '&#xe05f;',
			'icon-eye-2' : '&#xe060;',
			'icon-export-2' : '&#xe061;',
			'icon-microphone-2' : '&#xe062;',
			'icon-comment-3' : '&#xe063;',
			'icon-pencil' : '&#xe064;',
			'icon-directions-2' : '&#xe065;',
			'icon-bookmark-2' : '&#xe066;',
			'icon-search-2' : '&#xe067;',
			'icon-feather' : '&#xe068;',
			'icon-leaf-2' : '&#xe069;',
			'icon-music-3' : '&#xe06a;',
			'icon-signal' : '&#xe06b;',
			'icon-rss' : '&#xe06c;',
			'icon-quill' : '&#xe06d;',
			'icon-clock' : '&#xe06e;',
			'icon-compass' : '&#xe06f;',
			'icon-alarm-2' : '&#xe070;',
			'icon-hammer-2' : '&#xe071;',
			'icon-twitter' : '&#xe072;',
			'icon-wordpress' : '&#xe073;',
			'icon-wordpress-2' : '&#xe074;',
			'icon-headphones-2' : '&#xe075;',
			'icon-volume' : '&#xe076;',
			'icon-volume-2' : '&#xe077;',
			'icon-forward' : '&#xe078;',
			'icon-star-4' : '&#xe079;',
			'icon-arrow-up' : '&#xe07a;',
			'icon-arrow-down' : '&#xe07b;',
			'icon-arrow-left' : '&#xe07c;',
			'icon-arrow-right' : '&#xe07d;',
			'icon-comment-4' : '&#xe07e;',
			'icon-popout' : '&#xe07f;',
			'icon-tag-2' : '&#xe080;',
			'icon-star-5' : '&#xe081;',
			'icon-search-3' : '&#xe082;',
			'icon-trash' : '&#xe083;',
			'icon-upload' : '&#xe084;',
			'icon-cloud' : '&#xe085;',
			'icon-arrow-left-2' : '&#xe086;',
			'icon-arrow-down-2' : '&#xe087;',
			'icon-arrow-up-2' : '&#xe088;',
			'icon-arrow-right-2' : '&#xe089;',
			'icon-qq' : '&#xe08a;',
			'icon-instagram' : '&#xe08b;',
			'icon-renren' : '&#xe08c;',
			'icon-sina-weibo' : '&#xe08d;',
			'icon-tag-3' : '&#xe08e;',
			'icon-eye-3' : '&#xe08f;',
			'icon-location-4' : '&#xe090;',
			'icon-star-6' : '&#xe091;',
			'icon-grass' : '&#xe092;',
			'icon-tag-4' : '&#xe093;',
			'icon-comment-fill' : '&#xe094;',
			'icon-mail' : '&#xe095;',
			'icon-forward-2' : '&#xe096;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};